# ------------------------------------------------------------------------------
# Site Settings
# ------------------------------------------------------------------------------
theme: jekyll-theme-chirpy

# El idioma base para los layouts
lang: en

# ConfiguraciÃ³n de URLs (Solo una vez)
url: "https://martilian0.github.io"
baseurl: ""

# ------------------------------------------------------------------------------
# Polyglot Configuration
# ------------------------------------------------------------------------------
plugins:
  - jekyll-polyglot
  - jekyll-redirect-from

languages: ["en", "es", "fr", "br"]
default_lang: "en"
# Evita que Polyglot intente traducir archivos de sistema o assets
exclude_from_localization: ["javascript", "images", "assets", "sitemap", "public", "css"]
parallel_localization: false
relativize_urls: false

# ------------------------------------------------------------------------------
# Metadata & Social
# ------------------------------------------------------------------------------
title: notMarty
tagline: "Portfolio y proyectos personales."
description: >-
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

timezone: America/Santiago

github:
  username: martilian0

social:
  name: Martin Abarca Urtubia.
  email: m.abarca.urtubia@gmail.com
  links:
    - https://github.com/martilian0

# ------------------------------------------------------------------------------
# Website Customization
# ------------------------------------------------------------------------------
avatar: '/assets/profilepic/profilepic.jpg'
theme_mode: # [light | dark]
toc: true
paginate: 10

# ------------------------------------------------------------------------------
# Build Settings (No modificar a menos que sea necesario)
# ------------------------------------------------------------------------------
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      # Estructura de enlace para que Polyglot lo encuentre en cualquier idioma
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
  - node_modules
  - vendor
